2020-12-07 22:23:07,483 - CRITICAL - config_client_log.py - Критическая ошибка
2020-12-07 22:23:07,483 - ERROR - config_client_log.py - Ошибка
2020-12-07 22:23:07,483 - DEBUG - config_client_log.py - Отладочная информация
2020-12-07 22:23:07,483 - INFO - config_client_log.py - Информационное сообщение
2020-12-08 22:10:09,780 - INFO - client.py - Запущено соединение с сервером 127.0.0.1 на порт 8888
2020-12-08 22:10:09,781 - DEBUG - client.py - Разбор ответа сервера {'response': 200}
2020-12-08 22:10:09,781 - DEBUG - client.py - Получен ответ от сервера 200 : OK
2020-12-08 22:18:57,061 - INFO - client.py - Запущено соединение с сервером 127.0.0.1 на порт 8888
2020-12-08 22:18:57,062 - DEBUG - client.py - Разбор ответа сервера {'response': 200}
2020-12-08 22:18:57,062 - DEBUG - client.py - Получен ответ от сервера 200 : OK
2020-12-08 22:33:29,951 - INFO - client.py - Запущено соединение с сервером 127.0.0.1 на порт 8888
2020-12-08 22:33:29,951 - DEBUG - client.py - Разбор ответа сервера {'response': 200}
2020-12-08 22:33:29,951 - DEBUG - client.py - Получен ответ от сервера 200 : OK
2020-12-08 23:30:59,342 - INFO - client.py - Запущено соединение с сервером 127.0.0.1 на порт 8888
2020-12-08 23:30:59,343 - DEBUG - client.py - Разбор ответа сервера {'response': 200}
2020-12-08 23:30:59,343 - DEBUG - client.py - Получен ответ от сервера 200 : OK
